### ISSUE TITLE
就知道你们会搞这种事情

### ISSUE THREAD

**Issue by Wolf-Tungsten** [heyiWF/SEUAutoDailyReport#1]
所以我们在东南学工上加了验证码。

**Comment by Sciroccogti** [comment]
> 所以我们在东南学工上加了验证码。

哪有验证码啊，是提报的时候要填吗

**Comment by badcodebuilder** [comment]
不得不说我东需要一个像样的app来集成这些功能，总是微信、网站实在是不方便（虽然开发总是漫长的

**Comment by Wolf-Tungsten** [comment]
我们正在扩展小猴偷米 App来容纳这些应用。



靡不有初&nbsp;鲜克有终


------------------ 原始邮件 ------------------
发件人: CallMeChinese <notifications@github.com&gt;
发送时间: 2020年5月8日 22:22
收件人: heyiWF/SEUAutoDailyReport <SEUAutoDailyReport@noreply.github.com&gt;
抄送: 狼剩子 <canis.tungsten@foxmail.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[heyiWF/SEUAutoDailyReport] 就知道你们会搞这种事情 (#1)





 
不得不说我东需要一个像样的app来集成这些功能，总是微信、网站实在是不方便（虽然开发总是漫长的
